-sandbox
<div style="text-align: center; line-height: 0; padding-top: 9px;">
  <img src="https://databricks.com/wp-content/uploads/2018/03/db-academy-rgb-1200px.png" alt="Databricks Learning" style="width: 600px; height: 163px">
</div>

## Intro to Neural Networks with Keras

Before you attempt to throw a neural network at a problem, you want to establish a __baseline model__. Often, this will be a simple model, such as linear regression. Once we establish a baseline, then we can get started with Deep Learning.

Objectives:
* Intro to Keras
   * Sequential Model
   * Epochs
   * Visualize Loss

Let's start by making a simple array of features, and the label we are trying to predict is y = 2*X + 1 (with a little gaussian noise added to it).

In [4]:
import numpy as np
np.random.seed(0)

np.set_printoptions(suppress=True)

X = np.arange(-10, 11).reshape((21,1))
y = 2*X + 1 + np.random.normal()

list(zip(X, y))

Out[ 1 ]: 
[(array([-10]), array([-17.23594765])),
 (array([-9]), array([-15.23594765])),
 (array([-8]), array([-13.23594765])),
 (array([-7]), array([-11.23594765])),
 (array([-6]), array([-9.23594765])),
 (array([-5]), array([-7.23594765])),
 (array([-4]), array([-5.23594765])),
 (array([-3]), array([-3.23594765])),
 (array([-2]), array([-1.23594765])),
 (array([-1]), array([0.76405235])),
 (array([0]), array([2.76405235])),
 (array([1]), array([4.76405235])),
 (array([2]), array([6.76405235])),
 (array([3]), array([8.76405235])),
 (array([4]), array([10.76405235])),
 (array([5]), array([12.76405235])),
 (array([6]), array([14.76405235])),
 (array([7]), array([16.76405235])),
 (array([8]), array([18.76405235])),
 (array([9]), array([20.76405235])),
 (array([10]), array([22.76405235]))]

In [5]:
import matplotlib.pyplot as plt
plt.plot(X, y, 'ro')
display(plt.show())

Use Sklearn to establish our baseline (for simplicity, we are using the same dataset for training and testing in this toy example, but we will change that later).

In [7]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X, y)

Out[ 3 ]: LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
from sklearn.metrics import mean_squared_error

y_pred = lr.predict(X)
mse = mean_squared_error(y, y_pred)
print(mse)

5.958717194794429e-30

### Visualize Predictions

In [10]:
plt.plot(X, y_pred)
display(plt.show())

## Keras

Now that we have established a baseline model, let's see if we can build a fully-connected neural network that can meet or exceed our linear regression model. A fully-connected neural network is simply a set of matrix multiplications followed by some non-linear function (to be discussed later). 

[Keras](https://keras.io/) is a high-level API to build neural networks, that supports the following backends: Tensorflow, Theano, and CNTK. 

It was released by Francois Challot in 2015, and is now the official high-level API of Tensorflow. Keras has over 250,000 users, and we will primarily use Keras in this course.

![Life Cycle](https://brookewenig.github.io/img/DL/Life-Cycle-for-Neural-Network-Models-in-Keras.png)

# 1. Define a N-Layer Network

Here, we need to specify the dimensions of our input and output layers. When we say something is an N-layer neural network, we count all of the layers except the input layer. The diagram below demonstrates a 3-layer neural network. 

A special case of neural network with no hidden layers and no non-linearities is actually just linear regression :).

![](https://brookewenig.github.io/img/DL/NN-Regression.jpg)

For the next few labs, we will use the [Sequential model](https://keras.io/getting-started/sequential-model-guide/) from Keras.

-sandbox
## In Depth

<img src="https://brookewenig.github.io/img/DL/Bias.png" style="height: 250px; margin: 10px; border: 1px solid #ddd; border-radius: 15px 15px 15px 15px; padding: 10px"/>

In [14]:
import tensorflow as tf
tf.set_random_seed(42) # For reproducibility

from keras.models import Sequential
from keras.layers import Dense

# The Sequential model is a linear stack of layers.
model = Sequential()

model.add(Dense(units=1, input_dim=1, activation='linear'))

We can check the model definition by calling `.summary()`. Note the two parameters - any thoughts on why there are TWO?

In [16]:
model.summary()

_________________________________________________________________
Layer (type) Output Shape Param # 
=================================================================
dense_3 (Dense) (None, 1) 2 
=================================================================
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________

# 2. Compile a Network

To [compile](https://keras.io/getting-started/sequential-model-guide/#compilation) the network, we need to specify the loss function and which optimizer to use. We'll talk more about optimizers and loss metrics in the next lab.

For right now, we will use `mse` (mean squared error) for our loss function, and the `adam` optimizer.

In [18]:
model.l


Out[ 31 ]: <keras.models.Sequential at 0x7faa7f67c550>

In [19]:
model.compile(loss='mse',
              optimizer='adam')

# 3. Fit a Network

Let's [train](https://keras.io/getting-started/sequential-model-guide/#training) our model on X and y.

In [22]:
model.fit(X, y, ep)

Epoch 1/1

21/21 [==============================] - 0s 5ms/step - loss: 16.4405
 Out[ 9 ]: <keras.callbacks.History at 0x7faac0bbb588>

And take a look at the predictions.

In [24]:
keras_pred = model.predict(X)
keras_pred

Out[ 19 ]: 
array([[ 13.221626 ],
 [ 11.899464 ],
 [ 10.577301 ],
 [ 9.255138 ],
 [ 7.932976 ],
 [ 6.610813 ],
 [ 5.2886505],
 [ 3.966488 ],
 [ 2.6443253],
 [ 1.3221626],
 [ 0. ],
 [ -1.3221626],
 [ -2.6443253],
 [ -3.966488 ],
 [ -5.2886505],
 [ -6.610813 ],
 [ -7.932976 ],
 [ -9.255138 ],
 [-10.577301 ],
 [-11.899464 ],
 [-13.221626 ]], dtype=float32)

In [25]:
def kerasPredPlot(keras_pred):
  plt.clf()
  plt.plot(X, y, 'ro', label='True')
  plt.plot(X, keras_pred, 'co', label='Keras Pred')
  plt.legend(numpoints=1)
  display(plt.show())
  
kerasPredPlot(keras_pred)

What went wrong?? Turns out there a few more hyperparameters we need to set. Let's take a look at [Keras documentation](https://keras.io/models/sequential/).

`epochs` specifies how many passes you want over your entire dataset. Let's increase the number of epochs, and look at how the MSE decreases.

Here we are capturing the output of model.fit() as it returns a History object, which keeps a record of training loss values and metrics values at successive epochs, as well as validation loss values and validation metrics values (if applicable).

In [27]:
history = model.fit(X, y, epochs=20) 

Epoch 1/20

21/21 [==============================] - 0s 4ms/step - loss: 412.3214
Epoch 2/20

21/21 [==============================] - 0s 60us/step - loss: 412.0722
Epoch 3/20

21/21 [==============================] - 0s 58us/step - loss: 411.8232
Epoch 4/20

21/21 [==============================] - 0s 64us/step - loss: 411.5742
Epoch 5/20

21/21 [==============================] - 0s 63us/step - loss: 411.3253
Epoch 6/20

21/21 [==============================] - 0s 64us/step - loss: 411.0765
Epoch 7/20

21/21 [==============================] - 0s 60us/step - loss: 410.8354
Epoch 8/20

21/21 [==============================] - 0s 56us/step - loss: 410.5867
Epoch 9/20

21/21 [==============================] - 0s 59us/step - loss: 410.3381
Epoch 10/20

21/21 [==============================] - 0s 58us/step - loss: 410.0897
Epoch 11/20

21/21 [==============================] - 0s 63us/step - loss: 409.8413
Epoch 12/20

21/21 [==============================] - 0s 64us/step - loss: 409.5934
Epoch 13/20

21/21 [==============================] - 0s 60us/step - loss: 409.3452
Epoch 14/20

21/21 [==============================] - 0s 61us/step - loss: 409.0970
Epoch 15/20

21/21 [==============================] - 0s 72us/step - loss: 408.8491
Epoch 16/20

21/21 [==============================] - 0s 56us/step - loss: 408.6011
Epoch 17/20

21/21 [==============================] - 0s 56us/step - loss: 408.3533
Epoch 18/20

21/21 [==============================] - 0s 55us/step - loss: 408.1056
Epoch 19/20

21/21 [==============================] - 0s 57us/step - loss: 407.8579
Epoch 20/20

21/21 [==============================] - 0s 55us/step - loss: 407.6104

In [28]:
import matplotlib.pyplot as plt

def viewModelLoss():
  plt.clf()
  plt.plot(history.history['loss'])
  plt.title('model loss')
  plt.ylabel('loss')
  plt.xlabel('epoch')
  display(plt.show())
viewModelLoss()

Let's try increasing the epochs even more.

In [30]:
history = model.fit(X, y, epochs=4000)

Epoch 1/4000

21/21 [==============================] - 0s 89us/step - loss: 407.3629
Epoch 2/4000

21/21 [==============================] - 0s 66us/step - loss: 407.1156
Epoch 3/4000

21/21 [==============================] - 0s 62us/step - loss: 406.8656
Epoch 4/4000

21/21 [==============================] - 0s 66us/step - loss: 406.6185
Epoch 5/4000

21/21 [==============================] - 0s 60us/step - loss: 406.3714
Epoch 6/4000

21/21 [==============================] - 0s 56us/step - loss: 406.1245
Epoch 7/4000

21/21 [==============================] - 0s 163us/step - loss: 405.8776
Epoch 8/4000

21/21 [==============================] - 0s 65us/step - loss: 405.6309
Epoch 9/4000

21/21 [==============================] - 0s 55us/step - loss: 405.3813
Epoch 10/4000

21/21 [==============================] - 0s 60us/step - loss: 405.1319
Epoch 11/4000

21/21 [==============================] - 0s 57us/step - loss: 404.8855
Epoch 12/4000

21/21 [==============================] - 0s 64us/step - loss: 404.6391
Epoch 13/4000

21/21 [==============================] - 0s 58us/step - loss: 404.3929
Epoch 14/4000

21/21 [==============================] - 0s 62us/step - loss: 404.1469
Epoch 15/4000

21/21 [==============================] - 0s 55us/step - loss: 403.9008
Epoch 16/4000

21/21 [==============================] - 0s 57us/step - loss: 403.6549
Epoch 17/4000

21/21 [==============================] - 0s 64us/step - loss: 403.4092
Epoch 18/4000

21/21 [==============================] - 0s 63us/step - loss: 403.1635
Epoch 19/4000

21/21 [==============================] - 0s 60us/step - loss: 402.9179
Epoch 20/4000

21/21 [==============================] - 0s 52us/step - loss: 402.6725
Epoch 21/4000

21/21 [==============================] - 0s 56us/step - loss: 402.4271
Epoch 22/4000

21/21 [==============================] - 0s 63us/step - loss: 402.1818
Epoch 23/4000

21/21 [==============================] - 0s 67us/step - loss: 401.9367
Epoch 24/4000

21/21 [==============================] - 0s 59us/step - loss: 401.6917
Epoch 25/4000

21/21 [==============================] - 0s 61us/step - loss: 401.4467
Epoch 26/4000

21/21 [==============================] - 0s 55us/step - loss: 401.2019
Epoch 27/4000

21/21 [==============================] - 0s 55us/step - loss: 400.9573
Epoch 28/4000

21/21 [==============================] - 0s 57us/step - loss: 400.7126
Epoch 29/4000

21/21 [==============================] - 0s 86us/step - loss: 400.4681
Epoch 30/4000

21/21 [==============================] - 0s 56us/step - loss: 400.2238
Epoch 31/4000

21/21 [==============================] - 0s 53us/step - loss: 399.9795
Epoch 32/4000

21/21 [==============================] - 0s 54us/step - loss: 399.7353
Epoch 33/4000

21/21 [==============================] - 0s 56us/step - loss: 399.4913
Epoch 34/4000

21/21 [==============================] - 0s 57us/step - loss: 399.2473
Epoch 35/4000

21/21 [==============================] - 0s 58us/step - loss: 399.0035
Epoch 36/4000

21/21 [==============================] - 0s 57us/step - loss: 398.7599
Epoch 37/4000

21/21 [==============================] - 0s 58us/step - loss: 398.5162
Epoch 38/4000

21/21 [==============================] - 0s 56us/step - loss: 398.2727
Epoch 39/4000

21/21 [==============================] - 0s 56us/step - loss: 398.0294
Epoch 40/4000

21/21 [==============================] - 0s 62us/step - loss: 397.7841
Epoch 41/4000

21/21 [==============================] - 0s 62us/step - loss: 397.5409
Epoch 42/4000

21/21 [==============================] - 0s 54us/step - loss: 397.2979
Epoch 43/4000

21/21 [==============================] - 0s 61us/step - loss: 397.0549
Epoch 44/4000

21/21 [==============================] - 0s 61us/step - loss: 396.8121
Epoch 45/4000

21/21 [==============================] - 0s 54us/step - loss: 396.5694
Epoch 46/4000

21/21 [==============================] - 0s 53us/step - loss: 396.3267
Epoch 47/4000

21/21 [==============================

Let's inspect how our model decreased the loss (MSE) as the number of epochs increases.

In [32]:
viewModelLoss()

Extract model weights. Wahoo! We were able to approximate y=2*X + 1 quite well! If we trained for some more epochs, we should be able to approximate this function exactly (at risk of overfitting of course).

In [34]:
print(model.get_weights())
predicted_w = model.get_weights()[0][0][0]
predicted_b = model.get_weights()[1][0]

print("predicted_w: ", predicted_w)
print("predicted_b: ", predicted_b)

[array([[1.5714902]], dtype=float32), array([2.5911062], dtype=float32)]
predicted_w: 1.5714902
predicted_b: 2.5911062

# 4. Evaluate Network

As mentioned previously, we want to make sure our neural network can beat our benchmark. In this case, it didn't (for a variety of reasons we will explore more later), but the goal was to demonstrate the process of building a neural network with Keras.

In [36]:
model.evaluate(X, y) # Prints loss value & metrics values for the model in test mode (both are MSE here)

21/21 [==============================] - 0s 808us/step
 Out[ 26 ]: 6.762667655944824

# 5. Make Predictions

In [38]:
keras_pred1 = model.predict(X)
keras_pred1

Out[ 27 ]: 
array([[-13.1237955 ],
 [-11.552305 ],
 [ -9.980815 ],
 [ -8.409325 ],
 [ -6.8378344 ],
 [ -5.266345 ],
 [ -3.6948545 ],
 [ -2.1233642 ],
 [ -0.55187416],
 [ 1.019616 ],
 [ 2.5911062 ],
 [ 4.162596 ],
 [ 5.7340865 ],
 [ 7.3055763 ],
 [ 8.877067 ],
 [ 10.448557 ],
 [ 12.020047 ],
 [ 13.591537 ],
 [ 15.163028 ],
 [ 16.734518 ],
 [ 18.306007 ]], dtype=float32)

In [39]:
kerasPredPlot(keras_pred1)

Alright, this was a very simple, contrived example. Let's go ahead and make this a bit more interesting in the next lab!

-sandbox
&copy; 2018 Databricks, Inc. All rights reserved.<br/>
Apache, Apache Spark, Spark and the Spark logo are trademarks of the <a href="http://www.apache.org/">Apache Software Foundation</a>.<br/>
<br/>
<a href="https://databricks.com/privacy-policy">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use">Terms of Use</a> | <a href="http://help.databricks.com/">Support</a>